//! Detection of minified and generated files.

/// Threshold for average line length to consider a file minified.
const MINIFIED_AVG_LINE_LENGTH: usize = 200;

/// Number of header lines to check for generation markers.
const HEADER_LINES_TO_CHECK: usize = 5;

/// Generation markers searched in file headers (case-insensitive).
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "auto-generated",
    "automatically generated",
    "do not edit",
    "generated by",
    "generated from",
    "this file is generated",
];

/// Check if file content appears to be minified.
///
/// A file is minified if the average length of non-blank lines exceeds
/// 200 characters.
pub(crate) fn is_minified(content: &str) -> bool {
    if content.is_empty() {
        return false;
    }

    let non_blank: Vec<&str> = content.lines().filter(|l| !l.trim().is_empty()).collect();
    if non_blank.is_empty() {
        return false;
    }

    let total_len: usize = non_blank.iter().map(|l| l.len()).sum();
    total_len / non_blank.len() > MINIFIED_AVG_LINE_LENGTH
}

/// Check if file content appears to be auto-generated.
///
/// Looks for generation markers in the first 5 non-blank lines of the file.
pub(crate) fn is_generated(content: &str) -> bool {
    if content.is_empty() {
        return false;
    }

    content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .take(HEADER_LINES_TO_CHECK)
        .any(|line| {
            let lower = line.to_lowercase();
            GENERATED_MARKERS
                .iter()
                .any(|marker| lower.contains(marker))
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_file_is_not_minified() {
        assert!(!is_minified(""));
    }

    #[test]
    fn empty_file_is_not_generated() {
        assert!(!is_generated(""));
    }

    #[test]
    fn short_lines_not_minified() {
        let content = "line1\nline2\nline3\n";
        assert!(!is_minified(content));
    }

    #[test]
    fn long_single_line_is_minified() {
        let long_line = "a".repeat(300);
        assert!(is_minified(&long_line));
    }

    #[test]
    fn mixed_lines_with_high_average_is_minified() {
        let long = "x".repeat(400);
        let short = "y".repeat(50);
        let content = format!("{long}\n{short}\n");
        // avg = (400 + 50) / 2 = 225 > 200
        assert!(is_minified(&content));
    }

    #[test]
    fn mixed_lines_below_threshold_not_minified() {
        let line1 = "x".repeat(150);
        let line2 = "y".repeat(100);
        let content = format!("{line1}\n{line2}\n");
        // avg = 125 < 200
        assert!(!is_minified(&content));
    }

    #[test]
    fn detects_generated_marker_in_header() {
        let content = "// Code generated by protoc. DO NOT EDIT.\npackage main\n";
        assert!(is_generated(content));
    }

    #[test]
    fn detects_at_generated_marker() {
        let content = "// @generated\ncode here\n";
        assert!(is_generated(content));
    }

    #[test]
    fn detects_auto_generated() {
        let content = "/* Auto-Generated file */\nstuff\n";
        assert!(is_generated(content));
    }

    #[test]
    fn does_not_detect_generated_deep_in_file() {
        let mut lines = Vec::new();
        for i in 0..10 {
            lines.push(format!("line {i}"));
        }
        lines.push("// @generated".to_string());
        let content = lines.join("\n");
        assert!(!is_generated(&content));
    }

    #[test]
    fn blank_only_file_not_minified() {
        assert!(!is_minified("  \n\n  \n"));
    }
}
